---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 253d99053f80e4a368175e93b36edb662e7e5135  # frozen: v1.109.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 48dbc906f2ce7c0772cc8f106318831dee575de6  # frozen: 3.3.16
    hooks:
      - id: checkov
        args: [--config-file, ./configs/checkov.yml]

  - repo: https://github.com/Yelp/detect-secrets
    rev: 68e8b45440415753fff70a312ece8da92ba85b4a  # frozen: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline
          - ./configs/.secrets.baseline
          - --exclude-files
          - ^(\.pre-commit-config\.yaml|configs/\.secrets\.baseline)$

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "4025989e4fd50bb33592d7a3a4cfb3b46de9367a"  # frozen: v0.24.0
    hooks:
      - id: terraform-docs-go
        name: terraform-docs (root)
        language_version: "1.25.0"
        args:
          - "markdown"
          - "table"
          - "--output-file"
          - "README.md"
          - "."
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 321478e58f4938179c6b86e4ddfa923d1547a49b  # frozen: v0.16.6
    hooks:
      - id: ruff
        args: [--fix, --config=./configs/ruff.toml]
      - id: ruff-format
        args: [--config=./configs/ruff.toml]
